version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "timothyjoo"
    labels:
      - "dependencies"
      - "frontend"
    groups:
      react:
        patterns:
          - "react"
          - "react-*"
          - "@types/react*"
      testing:
        patterns:
          - "*test*"
          - "*jest*"
          - "@testing-library/*"
      build-tools:
        patterns:
          - "vite*"
          - "webpack*"
          - "babel*"
          - "eslint*"
          - "prettier*"

  # Backend dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "timothyjoo"
    labels:
      - "dependencies"
      - "backend"
    groups:
      fastapi:
        patterns:
          - "fastapi*"
          - "uvicorn*"
          - "pydantic*"
      database:
        patterns:
          - "sqlalchemy*"
          - "alembic*"
          - "psycopg*"
      testing:
        patterns:
          - "pytest*"
          - "coverage*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "timothyjoo"
    labels:
      - "dependencies"
      - "ci-cd"

  # Docker
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "timothyjoo"
    labels:
      - "dependencies"
      - "docker"
      - "frontend"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "timothyjoo"
    labels:
      - "dependencies"
      - "docker"
      - "backend"