version: '3.8'

services:
  # Azure Cosmos DB Emulator for local development
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: brainflowy-cosmosdb
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1
    ports:
      - "8081:8081"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
    volumes:
      - cosmos-data:/data/db
    networks:
      - brainflowy-network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: brainflowy-backend
    ports:
      - "8000:8000"
    environment:
      - COSMOS_ENDPOINT=https://cosmosdb:8081
      - COSMOS_KEY=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    depends_on:
      - cosmosdb
    networks:
      - brainflowy-network
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: brainflowy-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - brainflowy-network
    command: npm run dev -- --host

volumes:
  cosmos-data:

networks:
  brainflowy-network:
    driver: bridge