name: Deploy Backend Simple

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-simple.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements-deploy.txt -t .
    
    - name: Create deployment package
      run: |
        cd backend
        zip -r ../backend.zip . -x "*.pyc" -x "__pycache__/*" -x ".pytest_cache/*" -x "tests/*" -x "venv/*" -x ".env" -x "*.db"
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'brainflowy-backend'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: backend.zip